### ISSUE TITLE
window7 下 无法替换 app.asar 

### ISSUE THREAD

**Issue by bzzkb** [zce/asar-updater#1]
你好，非常感谢您提供的npm包，我阅读了源码，使用后，使用了各种方法，但在win7 下无法完成替换，报如下错误：估计是进程被占用了，期望大哥能给点思路，thank you 

{ Error: EBUSY: resource busy or locked, unlink 'E:\a_ab\resources\app.asar'
    at Error (native)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'E:\a_ab\resources\app.asar' }
{ Error: EPERM: operation not permitted, rename 'E:\a_ab\resources\update.asar' -> 'E:\a_ab\resources\app.asar'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'E:\a_ab\resources\update.asar',
  dest: 'E:\a_ab\resources\app.asar' }

**Comment by zce** [comment]
Windows肯定不能热替换，不用试了，我试了很久，我是用一个微内核去替换，你参考参考：https://github.com/zce/electron-boilerplate/blob/vue/build/index.js，不行加我微信：WEDN-NET
