### ISSUE TITLE
更新app.asar 找不到正确路径？

### ISSUE THREAD

**Issue by yansenlei** [zce/asar-updater#2]
```js
updater.setFeedURL(path.join(__dirname, 'app.asar'), 'http://git.oschina.net/wedn/ebp/raw/vue/latest/data.json')
```

这样会找不到正确路径？ `Applications/app/Contents/Resources/app.asar/dist/app.asar`

**Comment by zce** [comment]
按照你的描述，你的 `app.asar` 文件应该在 `Resources` 目录，而你在代码中通过 `__dirname` 拿到的应该是 `/Applications/app/Contents/Resources/app.asar/dist/`。

你可以参考我之前写的 Electron 项目模板中对 asar-updater 的使用：
https://github.com/zce/electron-boilerplate/blob/vue/app/backgrounds/update.js

**Comment by yansenlei** [comment]
fix [electron-basic-updater](https://github.com/TamkeenLMS/electron-basic-updater) can do it.
